# Generated by Django 3.0 on 2019-12-08 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIKey', '0002_apikey2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.CharField(default='123', max_length=11)),
            ],
        ),
        migrations.DeleteModel(
            name='APIKey',
        ),
        migrations.AddField(
            model_name='apikey2',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APIKey.Test'),
        ),
    ]
